### ISSUE TITLE
No need to rerun the whole setup

### ISSUE THREAD

**Issue by ares** [theforeman/ansible-foreman_scap_client#3]
[Here](https://github.com/theforeman/ansible-foreman_scap_client/blob/master/tasks/main.yml#L27) we seem to rerun the whole setup, which can be quite slow. Could we use https://docs.ansible.com/ansible/latest/modules/set_fact_module.html instead? That way we don't need to even mess with /etc/ansible/facts.d I think.

**Comment by xprazak2** [comment]
Using `set_fact` was my initial approach as well, but it meant executing commands to run script on target machines and idempotency tests were failing on that ([details](https://github.com/ansible/molecule/issues/1709)). So if we want to go this way, we would need to remove the idempotency check from our tests.

Since the file to gather facts we need is deployed once and then never changes, I think we can have:

```yml
- name: 'Create custom facts file'
  copy:
    src: foreman_scap_client_facts.rb
    dest: /etc/ansible/facts.d/foreman_scap_client.fact
    mode: 0755
  register: facts

- name: 'Re-run setup to use custom facts'
  setup: ~
  when: facts.changed
```
Which would mean the setup re-run will happen only the first time role is applied to host.
